### ISSUE TITLE
Height calculation is off?

### ISSUE THREAD

**Issue by lee-dohm** [fundon/atom-minimap#192]
Atom v0.167.0-a9c0553 on Mac OS X 10.10.1 using 27" Retina iMac

Apologies in advance for the huge image:

![minimap-height](https://cloud.githubusercontent.com/assets/1038121/5623749/a3f10db6-950d-11e4-94bd-55a1272a9bc2.png)

**Comment by lee-dohm** [comment]
I have the following in my `styles.less`:

```less
@ui-font-size: 14px;

atom-workspace {
  font-family: 'Helvetica Neue', sans-serif;
  font-size: @ui-font-size;
}
```

I suspect that with the change in how the minimap is attached to the editor view, this style may now affect the size of the minimap text (which does appear larger) and is therefore throwing off the size calculations.
